apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  host: host.name
  path: /
  tls:
    termination: edge
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None